# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hazardawareness Blog
email: paddy@hazardawaress.com.au
description: > # this means to ignore newlines until "baseurl:"
  Website design, branding and start up advice from a Perth based deisgn and development specialist.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://hazardawareness.com.au" # the base hostname & protocol for your site
twitter_username: paddy_hazard
github_username:  hazardawareness

# Build settings
markdown: kramdown
